name: Fictional world files

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Fictional world files
        run: |
          mkdir -p fictional-world-files
          cp FictionalWorld/zipped_version.zip fictional-world-files/
          cp FictionalWorld/countries.png fictional-world-files/

      - name: Upload FW artifact
        uses: actions/upload-artifact@v4
        with:
          name: fictional-world-files
          path: fictional-world-files/
          retention-days: 1
